### ISSUE TITLE
Issue5: xây dựng API và một trang web quản lý hiển thị trên app react

### ISSUE THREAD

**Issue by dangdu259e** [dangdu259e/SE04-Nhom20.2#10]

**Comment by dangdu259e** [comment]
dudt- đã xây dựng xong trang web api thực hiện kiểm tra user đăng nhập và tạo mới user

**Comment by dangdu259e** [comment]
https://github.com/dangdu259e/flaskbackend

**Comment by dangdu259e** [comment]
mình và @nguyenanhthu2510  đã hoàn thành api

**Comment by nguyenanhthu2510** [comment]
xây dựng api cho đối tượng cat bao gồm: tạo mới, sửa, xoá, lưu trữ db
