### ISSUE TITLE
Issue1: Tìm hiểu về các component react native

### ISSUE THREAD

**Issue by dangdu259e** [dangdu259e/SE04-Nhom20.2#6]
mình đang sử dụng tài liệu này để tìm hiểu về component:
_https://reactnative.dev/docs/intro-react-native-components_

**Comment by nguyenanhthu2510** [comment]
Tìm hiểu kết hợp tạo ra các Views trên ứng dụng

**Comment by nguyenanhthu2510** [comment]
t đang thiết kế gần xong view, sẽ cố gắng xong trong tuần này

**Comment by nguyenanhthu2510** [comment]
các bạn đợi t up code lên nhé, đang mắc mấy thứ của git

**Comment by dangdu259e** [comment]
okii

**Comment by nguyenanhthu2510** [comment]
t vừa push code lên branch thuna r nhé, các bạn lên ktra chạy thử xem cần góp ý gì ko. Chắc chắn cần chỉnh sửa nhiều nhg đây là view ban đầu thôi nhé, còn chỗ back lại trên top app vẫn bị quay lại phần splash nên cái đấy chỉnh sau nha
