### ISSUE TITLE
Issue2: Xây dựng giao diện Login

### ISSUE THREAD

**Issue by dangdu259e** [dangdu259e/SE04-Nhom20.2#7]
sử dụng các component react native xây dựng một giao diện login

**Comment by nguyenanhthu2510** [comment]
Đã xây dựng 1 giao diện mở đầu chương trình

**Comment by nguyenanhthu2510** [comment]
đã tạo splash screen

**Comment by nguyenanhthu2510** [comment]
finished

**Comment by dangdu259e** [comment]
xác nhận đã hoàn thành giao diện login
